### ISSUE TITLE
如何在打包文件中生成commit_hash文件

### ISSUE THREAD

**Issue by apm29** [a1067111756/git-revision-vite-plugin#1]
看文档说明是生成全局变量，有没有一种可能，可以在打包时生成一个commit_hash文件，内容是commit的hash 🔢

**Comment by a1067111756** [comment]
抱歉忙于工作很久没关注，生产一个commit_hash文件是可以的，git-revision-webpack-plugin的原理就是生成commit_hash文件。要实现这个目的，就需要你自己手动修改这个插件了，在git的钩子中读取到相关信息后手动创建一个commit_hash文件写入。我不太清楚你的使用场景，我自己使用时候是为了在代码中读取到git的信息，比如在控制台输出当前git提交记录，所以是以全局变量形式注入。当然你可以根据你自己的应用场景对插件进行修改来实现目的

**Comment by a1067111756** [comment]
我发现vite的define也会在打包文件中生成commit_hash文件，你可以在打包文件中查看下是否是你需要的
